# 4.5.1

vd4.5.1.1

In [ ]:
import pandas as pd
import numpy as np
rng=np.random.RandomState(100) #Tạo một mảng NumPy ngẫu nhiên cố định
arr1=rng.randint(0,10,4) #mảng NumPy 1 chiều 4 số ngẫu nhiên từ 0->10
arr2=rng.randint(0,10,(3,4)) #mảng 2 chiều 3x4 các số ngẫu nhiên từ 0->10, k lấy 10

In [2]:
arr1

array([8, 8, 3, 7], dtype=int32)

In [3]:
arr2

array([[7, 0, 4, 2],
       [5, 2, 2, 2],
       [1, 0, 8, 4]], dtype=int32)

In [4]:
sr=pd.Series(arr1) #Tạo một Series Pandax từ mảng Numpy arr1
df=pd.DataFrame(arr2,columns=['A','B','C','D']) #Tạo DataFrame từ arr2
print("Series:\n",sr)
print("DataFrame:\n",df)

Series:
 0    8
1    8
2    3
3    7
dtype: int32
DataFrame:
    A  B  C  D
0  7  0  4  2
1  5  2  2  2
2  1  0  8  4


vd4.5.1.2a

In [5]:
import pandas as pd
import numpy as np
s1=pd.Series([2,4,6], index=['a','b','c'])
s2=pd.Series([1,3,5], index=['b','c','d'])

In [6]:
s1

a    2
b    4
c    6
dtype: int64

In [7]:
s2

b    1
c    3
d    5
dtype: int64

In [ ]:
s1+s2 # Phép cộng với việc căn chỉnh theo index

a    NaN
b    5.0
c    9.0
d    NaN
dtype: float64

In [9]:
s3=pd.Series([2,4,6], index=['a','b','c']) # Khởi tạo Series s3, với index a,b,c
s4=pd.Series([1,3,5], index=['b','c','d'])

In [10]:
s3

a    2
b    4
c    6
dtype: int64

In [11]:
s4

b    1
c    3
d    5
dtype: int64

In [12]:
s3.add(s4, fill_value=0)

a    2.0
b    5.0
c    9.0
d    5.0
dtype: float64

vd4.5.1.2.b

In [15]:
#Ví dụ 4.5.1.2 #Số liệu top 5 dân số tỉnh thành Việt Nam
population = pd.Series({'TP.Hồ Chí Minh':9411805,
'Hà Nội':8330830,
'Thanh Hóa':3720000,
'Nghệ An':3410000,
'Đồng Nai':3097107})
#Số liệu về top 5 diện tích tỉnh/thành Việt Nam
area=pd.Series({'Nghệ An':16493,
'Gia Lai':15536.9,
'Sơn La':14174.4,
'Đăk Lăk':13030.5,
'Thanh Hóa':11132.2})
print("Top 5 tỉnh/tp đông dân nhất Việt Nam 2023:\n",population)
print("Top 5 tỉnh/tp diện tích lớn nhất Việt Nam 2023:\n",area)

Top 5 tỉnh/tp đông dân nhất Việt Nam 2023:
 TP.Hồ Chí Minh    9411805
Hà Nội            8330830
Thanh Hóa         3720000
Nghệ An           3410000
Đồng Nai          3097107
dtype: int64
Top 5 tỉnh/tp diện tích lớn nhất Việt Nam 2023:
 Nghệ An      16493.0
Gia Lai      15536.9
Sơn La       14174.4
Đăk Lăk      13030.5
Thanh Hóa    11132.2
dtype: float64


vd4.5.1.3

In [13]:
#Tạo 2 Series A, B và tính tổng các giá trị
A=pd.Series([1,3,5],index=[0,1,2])
B=pd.Series([2,4,6],index=[1,2,3])
A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [14]:
#Sử dụng ufuncs, truyền tham số fill_value vào.
A.add(B,fill_value=0)

0    1.0
1    5.0
2    9.0
3    6.0
dtype: float64

vd4.5.1.4

In [17]:
#Tạo 2 DataFrame Adf, Bdf và tính tổng các giá trị
import pandas as pd
import numpy as np
Adf=pd.DataFrame(np.random.randint(0,10,(2,2)), columns=['A','B'])
Bdf=pd.DataFrame(np.random.randint(0,10,(3,3)),columns=['B','A','C'])
print("Adf:\n",Adf)
print("Bdf:\n",Bdf)
print("\nAdf+Bdf: \n", Adf+Bdf)

Adf:
    A  B
0  6  8
1  0  8
Bdf:
    B  A  C
0  4  4  8
1  1  2  0
2  9  4  8

Adf+Bdf: 
       A     B   C
0  10.0  12.0 NaN
1   2.0   9.0 NaN
2   NaN   NaN NaN


In [18]:
print("Adf+Bdf(filled A):\n", Adf.add(Bdf,fill_value=0))

Adf+Bdf(filled A):
       A     B    C
0  10.0  12.0  8.0
1   2.0   9.0  0.0
2   4.0   9.0  8.0


# 4.5.2 Xử lý dữ liệu giữa Series và Dataframe

vd4.5.2.1

In [19]:
#Tạo một mảng NumPy 2 chiều (3,4) từ 10 phân tử ngẫu nhiên 0-->9
arr = np.random.randint(10,size=(3,4))
arr

array([[8, 6, 5, 2],
       [7, 7, 6, 2],
       [5, 4, 1, 4]], dtype=int32)

In [22]:
arr[0]

array([8, 6, 5, 2], dtype=int32)

In [20]:
arr-arr[0]

array([[ 0,  0,  0,  0],
       [-1,  1,  1,  0],
       [-3, -2, -4,  2]], dtype=int32)

In [21]:
#Tạo DataFrame df từ mảng NumPy arr, với các cột là P, Q, M, N
df = pd.DataFrame(arr,columns=['P','Q','M','N'])
print("df:\n",df)
#Tính toán hiệu của df với phần tử tương ứng trong hàng đầu của nó
df-df.iloc[0]

df:
    P  Q  M  N
0  8  6  5  2
1  7  7  6  2
2  5  4  1  4


P  Q  M  N
0  0  0  0  0
1 -1  1  1  0
2 -3 -2 -4  2

In [ ]:
df.iloc[0] # Lấy hàng đầu tiên của dataframe df dưới dạng series

P    8
Q    6
M    5
N    2
Name: 0, dtype: int32

In [24]:
df.iloc[0].index    #index of series lấy từ hnagf đầu tiên of dataframe df

Index(['P', 'Q', 'M', 'N'], dtype='object')

In [25]:
df.columns

Index(['P', 'Q', 'M', 'N'], dtype='object')

In [26]:
df.iloc[0].index=df.columns

In [27]:
df.iloc[0].name

0

In [28]:
df

P  Q  M  N
0  8  6  5  2
1  7  7  6  2
2  5  4  1  4

In [30]:
df-df.iloc[0]

P  Q  M  N
0  0  0  0  0
1 -1  1  1  0
2 -3 -2 -4  2

In [31]:
df

P  Q  M  N
0  8  6  5  2
1  7  7  6  2
2  5  4  1  4

In [32]:
df['Q'].index=df.index

# 4.5.3.Xử lý dữ liệu bị thiếu trong pandas

vd4.5.3.2

In [33]:
arr_nan=np.array([1,np.nan,3,4])
print(f"Mảng gốc: {arr_nan}")

Mảng gốc: [ 1. nan  3.  4.]


In [35]:
# Tính chất
arr_nan.sum(),arr_nan.max(), arr_nan.min()

(np.float64(nan), np.float64(nan), np.float64(nan))

In [37]:
#giải pháp nánum() (bỏ qua NaN)
np.nansum(arr_nan), np.nanmin(arr_nan)

(np.float64(8.0), np.float64(1.0))

vd4.5.3.3

In [38]:
import pandas as pd
sr_auto=pd.Series([1,2,np.nan,4,None])
sr

0    8
1    8
2    3
3    7
dtype: int32

vd4.5.3.6

In [40]:
data=pd.Series([1,np.nan,2,None,3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

# 4.6 chỉ mục phân cấp

VD4.6.1.1

In [1]:
import pandas as pd
#Tuples đại diện cho tỉnh thành phố - Năm tương ứng
index=[('Hà Nội',2015),('Hà Nội',2020),
 ('Nam Định',2015),('Nam Định',2020),
 ('Thanh Hóa',2015),('Thanh Hóa',2020),
 ('Đà Nẵng',2015),('Đà Nẵng',2020),
 ('Hồ Chí Minh',2015),('Hồ Chí Minh',2020)]
data=[ 7216000, 8246540,
 1850600, 1780330,
 3514200, 3664940,
 1028800, 1169480,
 8146300, 9227600]
vn_pop = pd.Series(data, index=index)
vn_pop

(Hà Nội, 2015)         7216000
(Hà Nội, 2020)         8246540
(Nam Định, 2015)       1850600
(Nam Định, 2020)       1780330
(Thanh Hóa, 2015)      3514200
(Thanh Hóa, 2020)      3664940
(Đà Nẵng, 2015)        1028800
(Đà Nẵng, 2020)        1169480
(Hồ Chí Minh, 2015)    8146300
(Hồ Chí Minh, 2020)    9227600
dtype: int64

vd4.6.1.2

In [2]:
vn_pop[('Hà Nội',2015):('Nam Định',2015)]

(Hà Nội, 2015)      7216000
(Hà Nội, 2020)      8246540
(Nam Định, 2015)    1850600
dtype: int64

In [3]:
vn_pop.index

Index([     ('Hà Nội', 2015),      ('Hà Nội', 2020),    ('Nam Định', 2015),
          ('Nam Định', 2020),   ('Thanh Hóa', 2015),   ('Thanh Hóa', 2020),
           ('Đà Nẵng', 2015),     ('Đà Nẵng', 2020), ('Hồ Chí Minh', 2015),
       ('Hồ Chí Minh', 2020)],
      dtype='object')

vd4.6.1.3 cách 1 sử dụng vòng lặp

In [4]:
vn_pop[[i for i in vn_pop.index if i[1]==2020]]

(Hà Nội, 2020)         8246540
(Nam Định, 2020)       1780330
(Thanh Hóa, 2020)      3664940
(Đà Nẵng, 2020)        1169480
(Hồ Chí Minh, 2020)    9227600
dtype: int64

vd4.6.1.4 thực hiệ chỉ mục phân cấp thông qua đối tượng đa chỉ mục/MultiIndex object

In [5]:
idx=pd.MultiIndex.from_tuples(index,
names=['Tỉnh/TP','Năm'])
idx

MultiIndex([(     'Hà Nội', 2015),
            (     'Hà Nội', 2020),
            (   'Nam Định', 2015),
            (   'Nam Định', 2020),
            (  'Thanh Hóa', 2015),
            (  'Thanh Hóa', 2020),
            (    'Đà Nẵng', 2015),
            (    'Đà Nẵng', 2020),
            ('Hồ Chí Minh', 2015),
            ('Hồ Chí Minh', 2020)],
           names=['Tỉnh/TP', 'Năm'])

vd4.6.1.5

In [6]:
vn_pop = vn_pop.reindex(idx)
vn_pop

Tỉnh/TP      Năm 
Hà Nội       2015    7216000
             2020    8246540
Nam Định     2015    1850600
             2020    1780330
Thanh Hóa    2015    3514200
             2020    3664940
Đà Nẵng      2015    1028800
             2020    1169480
Hồ Chí Minh  2015    8146300
             2020    9227600
dtype: int64

vd4.6.1.6

In [8]:
vn_pop[:,2020]

Tỉnh/TP
Hà Nội         8246540
Nam Định       1780330
Thanh Hóa      3664940
Đà Nẵng        1169480
Hồ Chí Minh    9227600
dtype: int64

Ví dụ 4.6.1.7. Chuyển Series thành DataFrame vn_pop_df.

In [9]:
vn_pop_df = vn_pop.unstack()
print('DataFrame dạng rộng (cột là Năm)')
display(vn_pop_df)

DataFrame dạng rộng (cột là Năm)


Năm             2015     2020
Tỉnh/TP                      
Hà Nội       7216000  8246540
Hồ Chí Minh  8146300  9227600
Nam Định     1850600  1780330
Thanh Hóa    3514200  3664940
Đà Nẵng      1028800  1169480

In [11]:
type(vn_pop_df)

pandas.core.frame.DataFrame

vd4.6.1.8

In [12]:
vn_pop_df.stack()

Tỉnh/TP      Năm 
Hà Nội       2015    7216000
             2020    8246540
Hồ Chí Minh  2015    8146300
             2020    9227600
Nam Định     2015    1850600
             2020    1780330
Thanh Hóa    2015    3514200
             2020    3664940
Đà Nẵng      2015    1028800
             2020    1169480
dtype: int64

In [13]:
type(vn_pop_df.stack())

pandas.core.series.Series

In [14]:
vn_pop.unstack()

Năm             2015     2020
Tỉnh/TP                      
Hà Nội       7216000  8246540
Hồ Chí Minh  8146300  9227600
Nam Định     1850600  1780330
Thanh Hóa    3514200  3664940
Đà Nẵng      1028800  1169480

vd4.6.2.1

In [16]:
import numpy as np
df = pd.DataFrame(np.random.rand(4,2),
 index=[['a','a','b','b'],[1,2, 1,2]],
 columns=['data1','data2'])
df

data1     data2
a 1  0.804211  0.273925
  2  0.592879  0.000432
b 1  0.440231  0.172309
  2  0.274003  0.717102

vd4.6.2.2

In [17]:
idx_arr=[['a','a','b','b'],[1,2,1,2]]
data=np.random.rand(4,3) #Tạo mảng dữ liệu ngẫu nhiên.
#Tạo đối tượng MultiIndex từ mảng idx_arr
multi_index=pd.MultiIndex.from_arrays(idx_arr,
 names = ['Data1','Data2'])
#Tạo DataFrame df.
df=pd.DataFrame(data,index = multi_index,
 columns=['Value1', 'Value2','Value3'])
df

Value1    Value2    Value3
Data1 Data2                              
a     1      0.800768  0.661240  0.473613
      2      0.186050  0.364649  0.310396
b     1      0.021071  0.351339  0.282766
      2      0.576325  0.624668  0.969941

vd4.6.2.3

In [18]:
#Tạo một danh sách các tuples.
idx_tuples=[('a',1),('a',2),('b',1),('b',2)]
data=np.random.randn(4,3) #Tạo mảng dữ liệu ngẫu nhiên.
df=pd.DataFrame(data,index=idx_tuples,
 columns=['Value1','Value2','Value3'])
df

Value1    Value2    Value3
(a, 1) -0.172910 -0.851993  0.060321
(a, 2)  2.028365 -2.540902  0.022688
(b, 1) -0.626407 -0.220242 -0.822277
(b, 2)  0.812267 -1.185986  0.666463

vd4.6.2.3.b

In [ ]:
#Tạo một danh sách các tuples.
idx_tuples=[('a',1),('a',2),('b',1),('b',2)]
data=np.random.randn(4,3) #Tạo mảng dữ liệu ngẫu nhiên.
# Tạo MultiIndex từ danh sách idx_tuples
multi_index_T = pd.MultiIndex.from_tuples(idx_tuples,
 names=['Level 1', 'Level 2'])
df=pd.DataFrame(data,index=multi_index_T,
 columns=['Value1','Value2','Value3'])
df

Value1    Value2    Value3
Level 1 Level 2                              
a       1       -0.487851  2.008850  0.991445
        2        0.128476 -1.094891 -0.146464
b       1       -0.139492  1.243322 -1.027975
        2        1.036846  0.904657 -0.238664

vd4.6.2.5

In [23]:
import pandas as np
import numpy as np
index=pd.MultiIndex.from_product([[2020,2021,2022],[1,2,3]],names=['Năm','Lần thi'])
columns=pd.MultiIndex.from_product([['Bình','Lan','Vân'],['Toán','Lý','Hóa']],names=['Học sinh','Môn học'])
#Tạo dữ liệu mẫu cho điểm số, là mảng kích thước 9x9 với các giá trị ngẫu nhiên từ 5-10
data=np.random.randint(5,10,(9,9))
'''Tạo DataFrame score với dữ liệu ngẫu nhiên từ mảng data kích thước 9x9 trong đó các chỉ
mục hàng (index) và cột(columns) được thiết lập'''
score=pd.DataFrame(data,index=index, columns=columns)
score

Học sinh     Bình         Lan         Vân       
Môn học      Toán Lý Hóa Toán Lý Hóa Toán Lý Hóa
Năm  Lần thi                                    
2020 1          8  7   5    8  7   7    7  9   8
     2          5  7   7    5  9   5    6  6   6
     3          6  5   8    7  6   7    5  6   6
2021 1          7  7   5    5  8   5    5  5   6
     2          8  8   8    8  7   7    8  6   5
     3          8  9   6    7  9   6    7  5   8
2022 1          5  7   9    9  9   6    8  5   5
     2          6  9   9    5  9   8    9  9   9
     3          7  5   5    7  8   8    9  5   8

vd4.6.2.6

In [24]:
score['Bình'] 

Môn học       Toán  Lý  Hóa
Năm  Lần thi               
2020 1           8   7    5
     2           5   7    7
     3           6   5    8
2021 1           7   7    5
     2           8   8    8
     3           8   9    6
2022 1           5   7    9
     2           6   9    9
     3           7   5    5

# 4.6.3. Indexing và Slicing trong MultiIndex 

# 4.7

In [26]:
import pandas as pd
sr1=pd.Series(['Đ','H','K','T'], index=[1,2,3,4])
sr2=pd.Series(['K','T','C','N'], index=[5,6,7,8])
pd.concat([sr1,sr2])

1    Đ
2    H
3    K
4    T
5    K
6    T
7    C
8    N
dtype: object

vd4.7.2.8 bổ sung

vd4.8.2.3